### ISSUE TITLE
Close to tray

### ISSUE THREAD

**Issue by sabrehagen** [flackr/circ#422]
Hi,

I'd like to make a feature request for 'close to tray' functionality. I realize being a chrome app this may not be possible, so the next best option would be 'close and reopen from chrome menu'. I desire this because I don't always want my CIRC window open, nor present in my window switcher.

Would this be possible given you're in the chrome app world?

**Comment by flackr** [comment]
As you guessed, close to tray is not possible as a chrome packaged app (See https://crbug.com/142450 for details). It would be possible to move the IRC connection to the background page so that it could be kept alive even when the app window is closed and this would let you close and reopen the app and continue to get notifications.

That being said, chrome packaged apps are being phased out on everything but ChromeOS (See https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html) so I have been focusing my available time on creating a Progressive Web App version of CIRC. This will require running a server component but through the magic of WebRTC does not require enabling port forwarding. See the server branch for current progress. This version will also let you close the app and continue to stay connected and receive notifications.
